### Place Order - Valid Request
POST http://localhost:3000/placeOrder
Content-Type: application/json

{
  "productId": "laptop-456",
  "orderQty": 1
}

### Place Order - Invalid Request (missing productId)
POST http://localhost:3000/placeOrder
Content-Type: application/json

{
  "orderQty": 3
}

### Place Order - Invalid Request (missing orderQty)
POST http://localhost:3000/placeOrder
Content-Type: application/json

{
  "productId": "laptop-456"
}


### Place Order - Invalid Request (negative orderQty)
POST http://localhost:3000/placeOrder
Content-Type: application/json

{
  "productId": "laptop-456",
  "orderQty": -1
}